config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true

    belongs_to :sub

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User


end

app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, :moderator_id, presence: true

    belongs_to :moderator,
        class_name: :User,
        foreign_key: :moderator_id

    has_many :posts
    
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token,  presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }
    
    has_many :subs,
        class_name: :Sub,
        foreign_key: :moderator_id

    has_many :posts,
        foreign_key: :author_id
        # class_name: :Post
    
    attr_reader :password
    after_initialize :ensure_token
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
        # self.reset_token!
        # self.save!
        self.password_digest
    end
    def valid_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
    def reset_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end
    def ensure_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def login(user)
        session[:session_token] = user.reset_token!
    end
    def logged_in?
        !!current_user
        # current_user.session_token == session[:session_token]
    end
    def logout
        current_user.reset_token!
        session[:session_token] = nil
    end
    def current_user
        @user = User.find_by(session_token: session[:session_token])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
  end

  def edit
  end

  def update

  end

  def index
  end

  private
  def post_params
    params.require(:post).permit(:title, :sub_id, :url, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.valid_password?(params[:user][:password])
            login(user)
            redirect_to subs_url
        else
            flash.now[:errors] = user.errors.full_messages
            render :new
        end
    end
    def destroy
        logout
        redirect_to new_session_url
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

    def require_moderator
        sub = Sub.find_by(id: params[:id])
        redirect_to subs_url unless sub && sub.moderator_id == current_user.id
    end

    before_action :require_moderator, only: [:edit, :update]
    def new
        @sub = Sub.new
    end
    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end
    def edit
        @sub = Sub.find_by(id: params[:id])
    end
    def update
        @sub = Sub.find_by(id: params[:id])
        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end
    def index
        @subs = Sub.all
        
    end
    def show
        @sub = Sub.find_by(id: params[:id])
    end
    private
    def sub_params
        params.require(:sub).permit(:title,:description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end
    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DBRedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if logged_in? %>
    <%=current_user.username%>
    <form action="<%=session_url%>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Sign Out">
    </form>
  <% end %>
  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form action="<%= sub_url(@sub) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <label> Title
        <input type="text" name="sub[title]" value="<%=@sub.title%>">
    </label>
    <label> Description
        <input type="text" name="sub[description]" value="<%=@sub.description%>">
    </label>
    <input type="submit" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h2>Index Subs</h2>

<% @subs.each do |sub| %>
    <form action="<%= sub_url(sub) %>" method="GET">
    <%= sub.title %> <%= sub.description %>
    <input type="submit" value="Show Sub">
    </form>
<% end %>

<a href="<%= new_sub_url %>">Create New Sub</a>

app/views/subs/new.html.erb
<h2>New Sub</h2>

<form action="<%=subs_url%>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label> Title
        <input type="text" name="sub[title]" value="<%=@sub.title%>">
    </label>
    <label> Description
        <input type="text" name="sub[description]" value="<%=@sub.description%>">
    </label>
    <input type="submit" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h2>Show Sub</h2>
<%= @sub.title %>
<%= @sub.description%>
<%= User.find_by(id: @sub.moderator_id).username %>
<form action="<%= edit_sub_url(@sub)%>" method="GET">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Edit Sub">
</form>

<a href="<%= subs_url %>">Index Subs</a>

app/views/users/new.html.erb
<% if !logged_in? %>
<form action="<%= new_session_url %>" method="GET">
    <!-- <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>"> -->
    <input type="submit" value="Sign In">
</form>
<% end %>
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label>
        Username:
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    <label>
        Password:
        <input type="text" name="user[password]" value="<%= @user.password %>">
    </label>
    <input type="submit" value="Sign Up">
</form>